apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes.noble-mutuwa.com-cert
spec:
  secretName: kubernetes.noble-mutuwa.com-tls
  dnsNames:
    - kubernetes.noble-mutuwa.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
